apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webpage-operator
rules:
  - apiGroups:
      - ""
    resources:
      - deployments
      - services
      - configmaps
      - pods
    verbs:
      - '*'
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - services
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - "sample.javaoperatorsdk"
    resources:
      - webpages
      - webpages/status
    verbs:
      - '*'
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - '*'