apiVersion: v1
kind: Service
metadata:
  name: ""
spec:
  selector:
    app: ""
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32111
  externalIPs:
    - 192.168.1.210